name: Java CI with Gradle

on:
  push:
    branches: [ main ] # Ensure this matches your development branch
  pull_request:
    branches: [ main ] # Ensure this matches your development branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set Spring Profile
        run: echo "SPRING_PROFILES_ACTIVE=ci" >> $GITHUB_ENV
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Run this job only on push to main
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Ensure this matches the id in your gradle settings for GitHub Packages
          settings-path: ${{ github.workspace }} # This might be needed if you're using Maven

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
